m-h-c-t/mh-helper-extension

- scripts/main.js
This PR extends the data gathered in Bristle Woods Rift. Records buffs, chamber state and acolyte phases.
---
Haven't tested it extensively so I don't think it's ready for merge, but would like a general feedback. In particular:
1. Naming of the sub states
2. Is it ok to use booleans or should I convert to number/labels?
---
Things left to do:
> BWRift detailed state

- scripts/main.js
When M400 is caught it disarms the cheese, but that breaks recording it's catch. Since it's only attracted to Fusion Fondue, this patch checks for the situation and manually sets the cheese for the hunt.
> Fix recording of M400 catches

- scripts/main.js
Current zone is recorded only if haven't changed zones. In that case just skip recording.
> Record Sunken City zone as hunt details

- scripts/main.js
Hi there Jack, just working through my [population to-do list](https://github.com/tsitu/MH-Tools/issues/79).
This PR addresses [#67](https://github.com/DevJackSmith/mh-hunt-helper/issues/67) and [#50](https://github.com/DevJackSmith/mh-hunt-helper/issues/50). For the latter, option 4 doesn't seem to be possible - max number of posters in inventory is 1 and you can't attract a Bounty Hunter while on one.
Is there anything that needs to be updated over on Server/intake.php, or will the backend automatically pick up new hunt_detail types/values?
> Implemented hunt_details for Gnawnian Express Station, Claw Shot City, and Harbour

- scripts/main.js
Pretty straightforward stage separation. Here are my notes for what mice can be attracted for reference:
`has_wall: false`
- [Rancid] Radioactive Blue: Gluttonous, Coffin, Ravenous, Zombie
- Undead [String] Emmental: Same as above + Zombot Unipire, Grave Robber
`has_wall: true`
- [Magical] [Rancid] Radioactive Blue: Black Widow, Monster, Giant Snail, Ghost, Bat, Vampire, Mummy
- Undead [String] Emmental: Zombot Unipire, Grave Robber, Ghost, Vampire, Mummy
- Crescent/Moon: Ghost, Bat, Vampire, Mummy, Lycan
- Crimson: Ghost, Bat, Vampire, Mummy, Mousevina von Vermin
> Added stages for Mousoleum rework

- scripts/main.js
- Requires the ` mouse` text to appear at the end of the input
- should be safe against future mice with Mouse as a standalone word not at the beginning or end of their name
- the preceding pattern ensures all text after the `</a>` is removed, so that if the game's name for it does include " Mouse", e.g. "Treasure Keeper Mouse", that the `$` condition is met.
> Fix bug where ` mouse` was not matched

- scripts/main.js
New "lucky catch" journal format introduces an additional closing bracket. Update the regex to include the `;` that is in HG's `<a href>` onclick function, to match it instead of the special font tag.
- Add lucky/not lucky catch information as a `hunt_detail`
> Update mouse name extraction regex

- scripts/popup.js
- Adds JSDoc, updated comments
- Activates MH tab for linked tools that use it or display pop-ups on it (map helpers, Tsitu tools)
- Reorder/update `findOpenMHTab` arguments
- Move standalone functions used only once to point-of-use definitions
- Add check for `chrome.runtime.lastError`, which is emitted by async functions (i.e. `sendMessage`).
- If the target tab can't/doesn't respond, e.g. the MH tab was removed, reloaded, etc, show this message
> Refactor popup.js code

- scripts/background.js
- Update comments
- Add some error handling re: messaging unavailable tabs & checking `chrome.runtime.lastError`
- Simplifies notification logic
- Improves timer accuracy by rounding to nearest minute, rather than flooring unconditionally. e.g. 6:59 is now reported as "7m" instead of "6m"
> Refactor background.js code

- .editorconfig
- README.md
- scripts/content.js
- scripts/main.js
Refs https://github.com/DevJackSmith/mh-hunt-helper/issues/91
- Success toast includes the total crowns and submittee's name
- Chrome still properly sets the DNT flag on the requests from the content script in my testing, in case users have enabled that
- This greatly reduces the clicks needed for MHCC admins and any users accustomed to the HornTracker behavior (as the extension now emulates it).
Possible follow-ups:
> Display crown count message after request resolves

- scripts/main.js
- Remove "Mysterious Anomaly" code as it is no longer relevant.
This implementation drops all birthday location hunts not done in one of the 4 rooms.
It's possible we should perform a "cheese check" since the location details / Larry tip strongly suggests that the stage only matters when `quest.items.coggy_colby_cheese.status === "active"` is true (i.e. non event cheese shares same pool, excepting SB+'s extra mouse.
I have the associated methods available for after prehunt goes live but won't add that until required via merge conflict.
> Capture stage for MH Birthday 2019

- scripts/content.js
Moved "Display Tsitu's Loader" logic inside the load event handler for `main.js` to prevent it from running before `main.js` is executed, which leaves the message event unhandled.
> Fixed inconsistent Auto-Loader bookmarklet injection

- scripts/background.js
- scripts/content.js
Refs DevJackSmith/mh-hunt-helper#98
I was unable to resolve the NetworkError with either `window.fetch`, `XMLHttpRequest`, adding `"*://script.google.com/*"` and `"webRequest"` to the extension manifests' `permissions`, and combinations thereof. 
I verified that, in `"no-cors"` mode, both Firefox and Chrome do actually make the submission to the Apps Script endpoint with my normal privacy-focused extensions both disabled and enabled, so I think this is OK.
I'm open to some other solution that makes it possible to know whether the request was even issued, but until then we'll have to settle for blind-firing the request. If we eventually add a way to query the user's crown history, then we could test via that method whether a new crown snapshot was recorded while still maintaining the …
> Switch to "no-cors" request to enable crown submissions from FF

- src/scripts/background.js
- Chrome explicitly notifies the extension when updates are available - no checking needed.
- Firefox has no browser support for the [`runtime.requestUpdateCheck` method](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/requestUpdateCheck)
- Firefox also [auto-updates AMO-hosted extensions](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Distribution#Distributing_your_add-on)
- Opera behavior is probably like Chrome, but doesn't really warrant any consideration anymore since their  update approval rate is slower than global warming
> Remove deprecated update checks

- src/scripts/main.js
The current WWR stage information is a string-based categorical variable for the 3 rage states. This PR adds a numerical value for each level, a true/false boolean for whether the attraction criteria is met (all >= 25), and the total rage sum.
It's possible the sum and boolean are unnecessary, as that information can conceivably be derived from the numerical levels in a SQL query.
I don't think knowing the numeric levels is important for other cheeses, which is why the cheese check is performed.
> Track WWR rage levels for Lactrodectus usage

- src/scripts/main.js
With these details, we can determine catch rates for the auto-catch mice, and compare catch rates before & after weakening, etc.
It's possible we could inspect other journal entries that came along in the activeturn response to determine if an autocatch ability activated on the given hunt, but that is not added here.
> Track Fort Rox upgrades & autocatch ability

- src/scripts/main.js
Checks the boss state and flags associated hunts. For the Minotaur Lair, tracks the number of catches made so far, the categorical label, and the rage bar width.
> Track Zokor mouse demoralization & Minotaur state

- src/manifest.json
- src/scripts/background.js
- src/scripts/content.js
This avoids invoking the NetworkError on Firefox, while still maintaining the isolation from other user extensions that was blocking submissions from occurring when submitted from the injected script.
Closes https://github.com/DevJackSmith/mh-hunt-helper/issues/98
> Submit crown counts via the background page

- src/scripts/main.js
- Report remaining mouse counts per wave, & if bosses are invincible.
- Report `morale` / `support_morale` fields, for Warpath Thrasher computations
- Report streak count, type, and whether the hunt extended it
> Add Fiery Warpath "hunt details"

- src/manifest.json
- src/scripts/main.js
hunt_details = { name: value, name: value, ...} can't be multiple levels deep. We can change that if we really need to, but i don't see a reason to yet. So fixing this one to be like all others.
Also forgot to commit version last time, so fixing that.
> Fixing hunt details object

- src/scripts/main.js
- Eggscavator Charge Level
- Whether egg loot is doubled (useful to know for those comparing charge cycles)
IIRC the charge egg dropped from the hunt was from the higher of the two states, pre- vs post-hunt. But I can't be certain, so it's tracking both. It's also possible this behavior changes/changed, and without knowing both pre/post, data sifters may draw the wrong conclusion. (This is also why I'm not bothering with the low/med/high; we could add that or back-calculate & update after we know more.)
> Add SEH hunt details

- src/scripts/main.js
Enables DB queries to distinguish between hunts with and without firing cannons
example hunt detail object for my horn from Gnawnia Rift with Lockbox Limburger armed:
> Add basic Halloween hunt details

- src/scripts/main.js
With the influx of Discord screenshots showcasing Desert Heater Base's ability to generate jackpot loots such as FW trap/portal parts, Launch Boxes, H/I essences, Aromatic Oils and more, I thought it'd be useful to piggyback off of the existing active horn response handling to parse DHB's bonus journal entry and submit it as a standard convertible.
[Sample HAR file for testing](https://github.com/mh-community-tools/mh-helper-extension/files/4044903/desert_heater_base.zip)
> Submit Desert Heater Base loot procs as convertible

- src/scripts/main.js
the shape of LNY.mice changed to an array, so accessing mice.costumed_* is now invalid
I have an example JSON blob of the "seeking costumed mice in order" state here: https://github.com/tehhowch/mh-helper-extension/commit/ad60f77b5ea559448711bc5fa1e21c17b5c021e5 (i removed some of the "rows" values)
> fix: avoid TypeError when determining LNY state

- src/scripts/main.js
Renamed relevant instances of `user.location` to `user.environment_name` in order to fix the current invalid `message.location`
If you notice any other breaking changes introduced with today's patch, feel free to commit on top of this PR.
> Fix breaking changes introduced by the 2020.01.28 patch

- src/scripts/main.js
Not adding a "getActiveBirthdayQuest" method since the event and its effects are localized, and the event may change format next year
> fix: Update quest name

- src/scripts/main.js
Also set aside augment tracking due to lack of a compelling use case
> Fixed Valour Rift hunt details logic

- src/scripts/main.js
This adds stage info and modifier info for Floating Islands. I have only tested this on the Law island, so more testing is probably required. 
Stage is the island display name eg. "Law island"
Hunt details contains the following:
*  Island Modifiers. These are the system identifiers for active modifiers eg. [ "empty_sky", "sky_cheese", "ore_bonus" ]. I could investigate changing this to the display name if needed. 
* BeforeWarden, AtWarden, AfterWarden - booleans
* enemy - The warden type if present
Any feedback welcome :)
> Add stage and hunt details for floating islands

- src/manifest.json
- src/scripts/main.js
Muridae (Artisan / Not Artisan), Slushy Shoreline (Softserve / Not Softserve), and Floating Islands (Warden) have new stages.
Floating Island's Warden stage is specifically for low altitude islands when the warden is the only mouse available.
> New stages -MM, SS, FI

- src/scripts/main.js
The regex for parsing the amount of loot had a group around the
thousands separator and subsequent digits. This caused the match
call to return the base match and the group result. After replacing
commas with nothing, this resulted in a very large number.
This was only an issue for loot items that can drop in amounts of 1000
or more, like Gold or Cursed Gold.
> Fix parsing the amount of loot when >999

- src/manifest.json
- src/scripts/main.js
Gold and points are not in the returned inventory object.
It also turns out we were not matching quantity on drops beyond the first in a list.
> Fix bad inventory

- src/scripts/background.js
- src/scripts/main.js
- Uses new data endpoint at `managers/ajax/pages/page.php`
- Checks for route changes to address #82 (especially important now that going from the "Friends" tab to a profile doesn't trigger a full page reload either)
- Auto-fetch and MHCC submit flow is only triggered upon freshly landing on a plain profile tab (excludes all other tabs/subtabs, including "King's Crowns")
> Fix MHCC crown tracking implementation

- src/scripts/main.js
Ref #109 
Things still parse properly:
> fix: Avoid stripping trap/base/charm/cheese unless at end of string

- .editorconfig
- .eslintrc.js
- .github/workflows/ci.yml
- .gitignore
- jsconfig.json
- package-lock.json
- package.json
- src/css/options.css
- src/scripts/background.js
- src/scripts/content.js
- src/scripts/main.js
- src/scripts/options.js
This PR doesn't do too much for us just yet, but is step 1 in a longer process that will introduce tests and better code quality
This PR
1. allows us to declare development tooling, via `devDependencies`
2. Adds a small bit of code style enforcement
- I chose not to enable rules for quote type or quoted object literal props, as we use both styles, and doing so here is a lot of noise
3. Creates two github workflows that provide some token level of feedback to contributions
- the lint job will fail if code is not valid javascript
- the test job will be useless until we have tests, but when we do (and make the package.json test script run them, then GitHub will automatically run tests on push & PR
4. Create a jsconfig.json project config, for those who use VS Code, which provides type …
> feat: create a development environment

- .eslintrc.js
- jsconfig.json
- package-lock.json
- package.json
- src/manifest.json
- src/scripts/background.js
- src/scripts/content.js
- src/scripts/main.js
TODO:
- Tweak payload sending logic to use the extension's message passing paradigm
- Specific tracking toggle for GWH/event submissions (Jack?)
---
FYI this year's parsing logic is the same as last year's. Feel free to test the extension on live golems - I've already submitted a handful over to tehhowch's intake sheet with no issues (ping him on Discord if you need access)
> GWH 2020 golem submission

- src/scripts/main.js
This is important to differentiate cell drops. They don't drop in the vault.
> Add vault/island in front of pirate designator

- src/scripts/main.js
Tested: Using Pecan Pecorino with no stage did parse correctly.
Not Tested: Other baits (should be N/A for the stage when no using a PP), golem submission.
> Updated for gwh 2021 changes

- src/scripts/main.js
That's no longer a thing!
FWIW, all of the LNY mice are still reported there, but they are now only listed with an `is_available` property (and all have the value `true`). We didn't use that property previously because the next-in-line mouse would be available even if it was the next required catch.
> fix(hunt-logic): Do not drop LNY hunts with event cheese before all LNY mice are caught

- src/scripts/main.js
Apparently Balack's Cove was refactored to use a quest instead of the old viewing_atts for game state. Simply pull the info from there instead.
> Fix addBalacksCoveStage to look at quest for info

- src/popup2.html
Removes links to out of date/failing sites such as HornTracker.
Updates Wiki & Tavern links to https.
> Update popup: Remove old links & update to https

- src/scripts/main.js
Pond stages are no longer needed. Chum status affects whether ink or pennies drop and people can figure this out by themselves (ala FI drops)
> removed pond stages

- .github/workflows/publish.yml
- Artifacts created from `dist` not `src`
- Remove `--id` option from FF submit step
> Correct publish workflow errors

- .eslintrc.js
- .vscode/extensions.json
- .vscode/settings.json
More dev ergonomics.
Since linting will make PRs fail, this will add vscode settings to recommend the [microsoft/vscode-eslint](https://github.com/microsoft/vscode-eslint) extension and fix files on save.
The `eslintrc.js` might need to filter the paths to `src` since it resulted in the `{args: 'none'}` change in itself. This might be trivial and not worth fixing though.
> Add .vscode recommendations for linting

- src/scripts/content.js
- src/scripts/main.js
One thing I dislike about the current submission success popup is that it's very intrusive. 
I think it's important to show these messages, both for confirmation that it was sent and also it makes you feel good providing data.
This PR moves the popup to the top of the screen. Makes it a bit bigger so it fits in nicely. Also changes to colors for named colors to actual hex codes to ensure consistency between browsers/OSes/etc. Actual color values have not been changed.
Happy to change the style / size of it.
> Improve message styling

- .github/workflows/publish.yml
- src/manifest.json
- src/scripts/content.js
- src/scripts/main.js
using forge library (cryptojs is no longer updated as far as i can tell, and recommends this one) https://github.com/digitalbazaar/forge
- adding hunter_id_hash on all requests to server
- tested against php hash 512, and it matches (string format)
- updated publish github action, to make sure the latest forge library is packed with the extension
- moved getSettings function up, since i need to use it earlier for debug messages
- moved debug mode activated check/message up
> Adding hunter_id hash to phase out hunter_id usage later

- src/scripts/main.js
Adds another handler case to `ajaxSuccess` so the hunter id hash can be refreshed on logins.
Previously, if a hunter navigated to mousehuntgame.com and logged in, the hash would still be set to '0'. If the user never hard refreshed the page (F5), then it would be possible to submit hunts with a hash of '0'.
Now if you navigate to mousehuntgame.com, it will silently continue without the alert but rely on the fact that the hash will be correctly set at login.
Closes: #235
> Create Hunter Id Hash on Login

- .eslintrc.js
- jest.config.js
- package-lock.json
- package.json
- tsconfig.json
Adding infrastructure files to allow unit testing with both `.js` and `.ts` files.
ESLint changes:
Allow exports from javascript files since browsers support it. Currently unused by any extension files.
Add the jest environemnt to js test files. Globals like `test`, `describe`, and `expect` are imported.
jest.config.js:
Jest can run without config files, but `ts-jest` is needed to compile `.ts` files.
We also configure importing path maps to simplify test file imports. i.e. `require('@scripts/file')` instead of `require('../../src/scripts/file')`)
> Add infra for running unit tests

- src/scripts/util/HornHud.ts
After release, it was found that the horn wasn't clicking in the way when run in debug mode.
Use the same delay as bradp, but in an async/await way
> Add small delay between horn mouse down and up

- src/scripts/types/hg.ts
Add initial typescript typings that will be used for other PRs.
I expect these types to change a lot as we discover what can and can't be null or undefined from the hg api responses.
> Add initial hg typings

- src/scripts/main.js
- src/scripts/modules/details/README.md
- src/scripts/modules/details/details.types.ts
- src/scripts/modules/details/environments/iceFortress.ts
- src/scripts/modules/details/index.ts
- tests/scripts/modules/details/environments/iceFortress.spec.ts
PR 2 of 2 for GWH
✔ need to rebase after PR 1 is merged (**done**)
✔️ Reviewable commit-by-commit (start with commit '[Draft extensible details feature](https://github.com/m-h-c-t/mh-helper-extension/pull/270/commits/2516bbf473e85064c630eb0630da6825e0627594))
Details is `./scripts/modules/details/`. Details can be environment specific or global (LNY, halloween, pillage etc.)
- `details.ts` contains typings
- `IDetailer` is the global detailer. Contains an `addDetails(message, pre, post, journal)`.
- `IEnvironmentDetailer` is an `IDetailer` but with the added `environment` property to match on.
- `index.ts` same as above, but exports `environmentDetailModules` and `globalDetailModules`
> Extensible details + GWH 2022 Details

- src/scripts/main.js
- src/scripts/modules/ajax-handlers/sbFactory.ts
- src/scripts/modules/stages/environments/forbiddenGrove.ts
- src/scripts/modules/stages/environments/superBrieFactory.ts
- src/scripts/modules/stages/index.ts
- src/scripts/types/hg.ts
- src/scripts/types/quests/forbiddenGrove.ts
- src/scripts/types/quests/index.ts
- tests/scripts/modules/ajax-handlers/sbFactory.spec.ts
- tests/scripts/modules/stages/environments/forbiddenGrove.spec.ts
- tests/scripts/modules/stages/environments/superBrieFactory.spec.ts
- Convert FG to stager
- Add tests for FG stager
This also fixes a bug when the user catches a Realm Ripper and `userPost.quests.QuestForbiddenGrove.grove.is_open` would result in a indexing error due to undefined quest.  
*Also creates a new stage called 'Realm Ripper Charm' similar to 'Softserve Charm' stage.*
---
- Only use boss_warning for sb factory stage
This was causing the post `IntakeMessage` stage to be 'Boss' when really it should be "Any Room" or one of the 4 pump rooms. 
Using the boss_warning to indicate stage fixes that.
---
- Don't log every birthday_factory request failure
birthday_factory.php is hit every time you open the vending machine and generates a warning. Move that logging to debug and warn only when purchases are unhandled.
> Convert Forbidden Grove staging

- src/scripts/hunt-filter/engine.ts
- src/scripts/main.js
While we do have a spreadsheet of mice that are slipping out of their stages, there are probably more than we can think of.
When a hunt is rejected and the reason is due to the stage or location changing, send the (pre + post) location, stage, and mouse that caused it so we can code an exception for it later.
Server side PR: https://github.com/m-h-c-t/mh-hunt-helper/pull/234
> Add rejection message intake

- src/scripts/main.js
- src/scripts/util/time.ts
- tests/scripts/util/time.spec.ts
- Add time util with tests
- Add timestamp to server messages if missing
I kept the timestamp grabbing process from the 'active hunt' journal entry. But I don't think it would take more than 1 second to process the hunt if we wanted to remove that as well.
> Add timestamps to all server messages

- src/scripts/util/HornHud.ts
Fix detection of sandwich board message title
Latest update gave a suite of new messages in the "sandwich board" area
but also changed some of the CSS classes since the message area was
converted into a templated view instead.
`huntersHornView__messageTitle` -> `hunterHornMessageView_title`
> Fix detection of King's Rewards

- src/scripts/modules/stages/environments/bountifulBeanstalk.ts
- tests/scripts/modules/stages/environments/bountifulBeanstalk.spec.ts
I expected the room to be named `Standard Lavish Lapis Room`, but if it's standard it just says `Lavish Lapis Room`.
So the stage ends up being `Dungeon - Lavish` instead of `Dungeon - Lavish Lapis`.
> Fix BB standard room stage name

- src/scripts/hunt-filter/exemptions/environments/bountifulBeanstalk.ts
- tests/scripts/hunt-filter/exemptions/environments/bountifulBeanstalk.spec.ts
Allow recording transition to Beanstalk boss when catching the new SB|+ mouse.
> Add new BB SB+ mouse to stage exception rule

- src/scripts/main.js
- src/scripts/modules/stages/environments/cursedCity.ts
- src/scripts/modules/stages/environments/lostCity.ts
- src/scripts/modules/stages/index.ts
- src/scripts/modules/stages/legacy.js
- src/scripts/types/hg.ts
- src/scripts/types/quests/index.ts
- src/scripts/types/quests/lostCity.ts
- tests/scripts/modules/stages/environments/lostCity.spec.ts
> Lost City stager

- src/scripts/hunt-filter/exemptions/environments/schoolOfSorcery.ts
- src/scripts/hunt-filter/exemptions/global.ts
- src/scripts/hunt-filter/exemptions/index.ts
- src/scripts/hunt-filter/messageRules.ts
- src/scripts/main.js
- src/scripts/modules/stages/environments/schoolOfSorcery.ts
- src/scripts/types/hg.ts
- src/scripts/types/quests/index.ts
- src/scripts/types/quests/schoolOfSorcery.ts
- src/scripts/util/HornHud.ts
- tests/scripts/hunt-filter/exemptions/environments/schoolOfSorcery.spec.ts
- tests/scripts/hunt-filter/exemptions/global.spec.ts
- tests/scripts/modules/stages/environments/schoolOfSorcery.spec.ts
- Prevent Horn sounding while there are active messages
- Add hunt filter exemption for charm or cheese running out
- Add School of Sorcery
> Add School of Sorcery stages

- src/scripts/content.js
- src/scripts/util/hornHud.ts
- **Remove HornHud undefined function call**
- **Use queue for multiple hud messages**
Multiple calls of `HornHud.showMessage` in a row would result in the previous message coming back and getting stuck. Implemented a queue system to process one message at a time.
> Fix sticky HUD messages

- src/scripts/modules/ajax-handlers/golem.ts
- src/scripts/modules/ajax-handlers/golem.types.ts
- src/scripts/util/constants.ts
- tests/scripts/modules/ajax-handlers/golem.spec.ts
Remove date gating and use Zod instead.
As long as the data parses successfully, then we can submit the golems.
> Validate GWH golem response with Zod

- src/options.html
- src/scripts/background.js
The `changeUserSettings` that changes values and returns the current settings was saving to the sync even when just requesting settings. This would unintentionally write all the default settings to `storage.sync` when upgrading to a new version.
- Fix `changeUserSettings` saving default settings every call
- Add floating save button to options
> Fix settings loss on update

- package.json
- src/scripts/background.js
Settings that were user changed to non-default and then changed back to default weren't being removed from the storage area.
> Fix for settings not saving

- src/scripts/background.js
Issue #615 - The icon url needed to be a url despite what it says in the docs.
> Fix chrome desktop notifications

- src/manifest.v3.chrome.json
- src/manifest.v3.firefox.json
We no longer use alarms so we no longer have the alarm permission.
> Removed alarm permission

- src/scripts/main.js
Relic hunter hints were not being submitted because the _v2 endpoint is now being used in-game.
> Updated endpoint for RH hints

- package-lock.json
- package.json
- src/scripts/main.js
- src/scripts/modules/ajax-handlers/ajaxSuccessHandler.ts
- src/scripts/modules/ajax-handlers/index.ts
- src/scripts/modules/ajax-handlers/treasureMap.ts
- src/scripts/types/hg/treasureMap.ts
- tests/scripts/modules/ajax-handlers/treasureMap.spec.ts
- **Add new base class for zod validated ajax success handlers**
- **Convert recordMap to new validated ajax success handler**
`AjaxSuccessHandlers` can now inherit from `ValidatedAjaxSuccessHandler` and define a Zod schema in a field. That schema will be used and if it matches will be pass down to a `validatedExecute` method. The data is guaranteed to match the defined schema! No more needing to assume data type.
This will eventually lead to the removal of event date flags!
> Validated Ajax Handlers w/ Treasure Map Example

- src/scripts/main.js
- src/scripts/modules/ajax-handlers/kingsGiveaway.ts
- src/scripts/modules/ajax-handlers/sbFactory.CheesyPipeParty.ts
- src/scripts/modules/ajax-handlers/sbFactory.ts
- src/scripts/modules/ajax-handlers/spookyShuffle.ts
- src/scripts/modules/ajax-handlers/springEggHunt.ts
- src/scripts/services/submission.service.ts
- tests/scripts/modules/ajax-handlers/kingsGiveaway.spec.ts
- tests/scripts/modules/ajax-handlers/sbFactory.CheesyPipeParty.spec.ts
- tests/scripts/modules/ajax-handlers/sbFactory.spec.ts
- tests/scripts/modules/ajax-handlers/spookyShuffle.spec.ts
- tests/scripts/modules/ajax-handlers/springEggHunt.spec.ts
- tests/scripts/services/submisssion.service.spec.ts
- **Refactor ajax handlers to use submission service**
- **Add hunt and rejection to submission service**
So my other PR wasn't too much, ajax handlers now use submission service directly instead of bound method.
> Use submission service in ajax handlers

- src/scripts/main.js
- src/scripts/modules/ajax-handlers/kingsGiveaway.ts
- src/scripts/services/api.service.ts
- src/scripts/services/mouserip-api.service.ts
- src/scripts/services/submission.service.ts
- tests/scripts/modules/ajax-handlers/kingsGiveaway.spec.ts
- tests/scripts/services/submisssion.service.spec.ts
Instead of using ApiService directly, it's smarter to create a wrapper for each website we reach out to. Exactly how SubmissionService uses ApiService and is exclusively for mhct.win.
KGA handling had two problems: one was accidentally sending a body on a GET request which isn't allowed in browsers and a zod related error was that the item property `item_id` was actually just `id`. 
I've fixed the docs on api.mouse.rip to reflect what the api actually returns.
> Add abstraction for mouse.rip API. Fix KGA handling.
