m-h-c-t/mh-helper-extension

scripts/main.js

Current year is tracked as stage, while boss status and furthest year are recorded as hunt details.

Track birthday 2018 area stage

---

options.html
scripts/options.js

- Update comments
- Inline event handler definitions
- Use dot notation per JSHint suggestion

Refactor options.js code

---

src/popup.html
src/popup2.html

- Rearranged link ordering
- Clarified descriptions
- Removed obsolete Friend Refresh link
- Added Useful Userscripts link ([#97](https://github.com/DevJackSmith/mh-hunt-helper/issues/97))

Updated popup.html and popup2.html

---

src/scripts/main.js

Re-opening https://github.com/DevJackSmith/mh-helper-extension/pull/63 (btw I don't have permission to delete that branch)
Stages:
- Cork Collecting
- Pressure Building
- Tiny Eruption
- Small Eruption
- Medium Eruption
- Large Eruption
- Epic Eruption

Added Queso Geyser stage separation

---

src/scripts/background.js
src/scripts/main.js

- Notification message was omitting any included plat + diamond crowns
Right now the platinum and diamond counts are ignored by the db (requires action by @DevJackSmith )

Update crown submission notification

---

src/scripts/main.js

The element is now `<span class="friendsPage-friendRow-titleBar-name" title="George Costanza">George Costanza</span>`

Fix selector for current profile's name

---

src/scripts/main.js

Records each floor as separate stage
TODO: ultimate umbra states are not checked.

Add stage and hunt details for Valour Rift

---

src/manifest.json
src/scripts/main.js

Tiny edit, the quest year changed.

Changed to 2019

---

src/scripts/main.js

- add background page logging for logic errors (as these persist through page navigation, etc)
- Split submission aspect out of 'recordConvertible' so it can be used elsewhere
- update 'getItem' to compute the output `id` from the input's `item_id` or `id` property

refactor: Switch split to regexp captures

---

src/scripts/main.js

The logic is virtually identical to https://github.com/mh-community-tools/mh-helper-extension/pull/76, with very minor changes to the regex.
[Sample HAR file for testing](https://github.com/mh-community-tools/mh-helper-extension/files/4107133/gilded-charm.zip)

Submit Gilded Charm procs as convertible

---

README.md
src/popup.html

- Removed the popup for Version History (updates.php, no longer maintained)
- Updated the link for Mouse Attraction Rates in the relevant popup (from https://www.agiletravels.com/ to https://www.agiletravels.com/attractions.php)

Updated Extension Popup

---

src/manifest.json
src/popup.html
src/scripts/main.js

with post to be able to fit more than 2000 characters. In my tests 45 mice were about 850 characters.

Fixing-map-helper-auto-submit

---

src/manifest.json
src/scripts/main.js

Marketplace.php was getting status code of 500 and causing a full page refresh. So we experimented with other options - Camp seems ok.

Changed pre-hunt information source

---

src/manifest.json
src/scripts/main.js

Adds pillage information to hunt_details

Pillage tracking

---

src/manifest.json
src/scripts/main.js

See issue #101 
This has a couple simple changes that could use some eyeballs and some testing.

Added pirate stages, richard stage. Needs testing

---

src/scripts/main.js

- add missing radix to parseInt call
Debug logs will now highlight items that weren't included in the reports, rather than silently dropping them:

refactor(addLoot): reduce indentation & add debug log

---

src/scripts/main.js

- move pillage tracking from `createMessageFromHunt` into own method, like lucky catches
- revert usage of `Object.assign` in location-specific hunt details methods (guaranteed no existing hunt details)
- fixes bug in Harbour hunt details
Ref #92 #103

refactor(hunt_details): always perform hunt_details calculations via `addHuntDetails` method

---

src/manifest.json
src/scripts/background.js
src/scripts/main.js

So we can more easily do the things we wish to do.
The backend & BigQuery are all set up & verified.. just needs a deployment!

Use a saner table schema

---

src/manifest.json
src/scripts/main.js

Did single tests - one with PP and one with ESB. Both submitted what I expected. I'm going to assume the boss stage still works.

Added N/A stage for non-event cheese to GWH for better aggregation

---

src/manifest.json
src/scripts/main.js

Added a hack to track those extra journal entries that aren't convertibles. Please make sure it's not an awful hack.

Sleigher tracking

---

src/manifest.json
src/scripts/main.js

New quest name and a check that we're using event cheese before assigning a room.

Updated for SB Factory 2021

---

src/manifest.json
src/scripts/main.js

Sbfactory2021

---

src/manifest.json
src/scripts/main.js

Watches the prize pack opening endpoint

Added logic for opening prize packs

---

src/manifest.json
src/scripts/main.js

Some fixes where item ids were not gotten and quantities were not integers.

Kga prize packs

---

.github/workflows/publish.yml
src/manifest.json
src/scripts/main.js
src/scripts/popup.js

also switched to "XX.XX.XX" instead of "vXX.XX.XX"

Default to test version instead of prod and increment version automatically

---

.github/workflows/ci.yml
.github/workflows/publish.yml

- Update action versions to latest
- Limit uses of `cd` in publish workflow
- Use env variables for repeated cURL arguments

refactor(workflows): Update workflow versions, steps

---

src/scripts/main.js

Some changes to how stages are calculated. This mostly affects pirates and their stage name.

Sky palace Refinements

---

.eslintrc.js
package-lock.json
package.json
src/scripts/main.js

Optional Chaining & nullish coalescing are further supported, to the point where we can be comfortable using them.

feat: update ESLint, syntax

---

src/scripts/main.js

Themes were festive, now they aren't. Updated the comparison appropriately.
Watch for "Toys yule log stat item" (for example) stage names until this propogates.

themes aren't festive now

---

src/scripts/main.js

Compiles, need to test as a submission.
Still needs the hunt_details to be added.
DO NOT APPROVE

Track cauldron procs

---

.github/workflows/ci.yml
package-lock.json
package.json

- Update workflows to use the latest Node LTS, 16
- Update the ESLint version to latest minor

chore(deps): update node & ESLint versions

---

.eslintrc.js
package-lock.json
package.json
src/scripts/main.js

Use new rule added in 8.14 to detect constant conditions when working with ??, ||, and &&
- rule will likely be added to eslint:recommended in ESLint v9

feat(lint): upgrade ESLint to 8.18

---

src/scripts/main.js

all mice currently show FG Closed. Don't know when this last time worked, so might want to wipe fg in db after we get some good data.

Fixing FG stage

---

.gitignore
src/scripts/main.js

Added stages for the farm and pond

Fofo release

---

src/scripts/main.js

Selectively-processed journals no longer need to worry about current timestamp or whether we're done processing active journal entries so I removed that logic.
While doing so it was noticed we're not getting convertible submissions and that was investigated and (probably) solved.

Cleanup selective journals; fix convertible submissions

---

src/css/options.css

setting range input color since it's not visible on some browsers

---

src/scripts/main.js

Cleanup selective journals

---

src/scripts/main.js

Tested, shared on discord. This addresses #194

coded fix, needed to test

---

.github/workflows/publish.yml

it might still say it failed sometimes, but usually it works anyway, so better to check status on the store.

Fixing ff upload

---

src/scripts/main.js

Halloween update had changes to the cauldron trap messages and processing.

added logic for gloomy boons

---

src/scripts/main.js

this is super modelled after cauldrons with just some minor edits.

An Attempt at recording Unstable procs

---

src/scripts/main.js

added the 3 area charms (magmatic crystal, black powder & dusty coal) to Daredevil Canyon

added daredevil canyon charms

---

src/scripts/main.js

Depot stage has a new substage. Some database cleanup can be done to move all no-rush stage hunts with the supply schedule charm armed into this new stage

Ges update

---

src/scripts/main.js

Torch charm procs

---

src/scripts/main.js

added gift wrapped charm

---

src/css/popup.css
src/popup.html
src/popup2.html

- made the hunt timer bigger and bolder
- combined few buttons to make the scroll go away
- thanks for all the help @bradp 
- also moved options into gear icon
- changed hover color and to be only over cell, not whole row

updated popup styling

---

src/popup.html

Added the missing .php to the donations link

Fixed donation link

---

.github/workflows/publish.yml
src/manifest.json
src/scripts/content.js
src/scripts/main.js

Built in API allows usage of basic hash functions without the use of third-party library
This fix was done because the main script was not being injected unless the forge library was correctly located in `dist/third_party/forge`. chrome.runtime.getURL would return undefined so the callback to load the main script never fired.

Use Web Crypto API instead of forge

---

src/scripts/content.js
src/scripts/main.js
webpack/webpack.dev.js
webpack/webpack.prod.js

- Change devtool for dev since eval() is CSP blocked
- Fix for always showing Tsitu Auto-Loader

Fix Tsitu Auto-Loader not auto-loading

---

src/scripts/main.js

Fixing tracking switch

---

src/scripts/background.js
src/scripts/content.js
src/scripts/main.js
src/scripts/popup.js

See #256
**Updates**
- Correctly counts down & checks for ready state
- Correctly sounds horn from alert
- Check for king's reward (still needs testing)

🎺  New horn updates

---

src/scripts/content.js
src/scripts/main.js
src/scripts/util/HornHud.ts

- Add utility class to interact with horn hud
- Use horn utility clas
- Add tests with DOM
Closes: #256

Add utility class to interact with new horn

---

.editorconfig
jest.config.js
package-lock.json
package.json
src/scripts/ajax-handlers/ajaxSuccessHandler.ts
src/scripts/ajax-handlers/golem.ts
src/scripts/ajax-handlers/golem.types.ts
src/scripts/background.js
src/scripts/content.js
src/scripts/main.js
tests/scripts/ajax-handlers/golem.spec.ts

Testing out moving ajaxSuccess handlers from main.js to their own little files/components.  
Everything to do with golems has been moved to `golems.ts`. Url matching, parsing the response, sending to google script, and showing result banner.
Each "handler" as two methods: `match` and `execute`.  
`match`: you are passed the xhr URL and you return a boolean if your handler can act on it (GWH also checks current time)
`execute`: do what you will with the xhr.responseJSON!
`golem.types.ts` contains all the type definitions
`golem.ts` is the implementation of the handler
The two external dependencies needed for golem submission are constructor injected. This is logging service and the showFlashMessage method to show the success/error banner.

GWH 2022 Module

---

.github/workflows/publish.yml
package-lock.json
package.json
src/manifest.json
src/options.html
src/scripts/background.js
src/scripts/content.js
src/scripts/options.js
webpack/webpack.common.js

- added webpack action to fetch latest css files from PotatoSalad repo with their permission https://github.com/MHCommunity/mh-dark-mode
- added toggle in the options and loader in the context.js
- also moved tsitus autoloader files from github action to webpack

Adding Dark Mode by PotatoSalad

---

package-lock.json
package.json

NPM gave some audit messages that dependabot didn't submit a PR for. One claimed breaking changes so I tested it.

confirmed audit fix worked

---

src/scripts/main.js
src/scripts/modules/stages/environments/iceFortress.ts
src/scripts/modules/stages/environments/superBrieFactory.ts
src/scripts/modules/stages/index.ts
src/scripts/types/hg.ts
src/scripts/types/quests/index.ts
src/scripts/types/quests/superBrieFactory.ts
tests/scripts/modules/stages/environments/iceFortress.spec.ts
tests/scripts/modules/stages/environments/superBrieFactory.spec.ts

- Move SBFactory to stager module
- Add tests for sb factory stager

SB+ Factory Stager

---

.github/CODEOWNERS

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

Adding default reviewers to all PRs

---

src/scripts/hunt-filter/exemptions/environments/bountifulBeanstalk.ts
src/scripts/modules/stages/environments/bountifulBeanstalk.ts
src/scripts/types/quests/bountifulBeanstalk.ts
tests/scripts/hunt-filter/exemptions/environments/bountifulBeanstalk.spec.ts
tests/scripts/modules/stages/environments/bountifulBeanstalk.spec.ts
tsconfig.json

- Add current room to BB stage
- Update BB filter exemptions due to new stage names
- Update exemption tests to use stager

Add Bountiful Beanstalk castle room name to stage

---

.eslintignore
.gitignore
jest.config.js

Turn on flag for code coverage. Hoping to turn on some coverage integrations for PRs down the line.

Enable code coverage reporting from jest

---

src/scripts/hunt-filter/exemptions/environments/clawShotCity.ts
src/scripts/hunt-filter/exemptions/index.ts
src/scripts/modules/stages/legacy.js
src/scripts/types/hg.ts
src/scripts/types/quests/clawShotCity.ts
src/scripts/types/quests/index.ts
tests/scripts/hunt-filter/exemptions/environments/clawShotCity.spec.ts

- Add Claw Shot City quest type
- Add bounty hunter reject test case
- Add stage exemption for Bounty Hunter catch

Add Bounty Hunter exemption

---

src/scripts/main.js

Update bookmarklet src replacement

---

src/scripts/hunt-filter/exemptions/environments/iceberg.ts
src/scripts/hunt-filter/exemptions/index.ts
src/scripts/modules/stages/legacy.js
src/scripts/types/hg.ts
src/scripts/types/quests/iceberg.ts
src/scripts/types/quests/index.ts
tests/scripts/hunt-filter/exemptions/environments/iceberg.spec.ts

* Added tests for iceberg rejections
* Added exemptions for generals, Icewing, and deep mice

Add Iceberg Exemptions

---

.github/workflows/publish.yml

- simplified date formatting
- added ssh to server step where it checks if version is already allowed, and if not, allows it
- created a new key pair just for github actions and set server connection info in github secrets
tested and it works

Automatic version allow

---

src/scripts/main.js
src/scripts/modules/stages/environments/harbour.ts
src/scripts/modules/stages/index.ts
src/scripts/modules/stages/legacy.js
src/scripts/types/hg.ts
src/scripts/types/quests/harbour.ts
src/scripts/types/quests/index.ts
tests/scripts/modules/stages/environments/harbour.spec.ts

- Add Harbour stage test
- Add Harbour stager

Harbour Stager

---

src/scripts/main.js

MP pull request had some errors. These two lines were converted to stagers

Fix merge error on staging funcs

---

src/scripts/main.js
src/scripts/modules/stages/environments/fieryWarpath.ts
src/scripts/modules/stages/index.ts
src/scripts/modules/stages/legacy.js
src/scripts/types/hg.ts
tests/scripts/modules/stages/environments/fieryWarpath.spec.ts

- Add Fiery Warpath stage test
- Add Fiery Warpath stager

Fiery Warpath stager

---

src/scripts/background.js

to fix upgrading to new version of eslint

Changed coalesce operator

---

package-lock.json
package.json
src/scripts/main.js
src/scripts/modules/ajax-handlers/beanstalkRoomTracker.ts
src/scripts/modules/ajax-handlers/beanstalkRoomTracker.types.ts
src/scripts/modules/ajax-handlers/index.ts
src/scripts/types/quests/bountifulBeanstalk.ts
tests/scripts/modules/ajax-handlers/bbCastleRoomTracker.spec.ts
tests/scripts/modules/stages/environments/bountifulBeanstalk.spec.ts

Posts data to here:
https://docs.google.com/spreadsheets/d/1LbuLBTexiLadmq1v76VBj0V-N3-xnwiIApBEaFetYdQ/edit?usp=sharing

Add ajax handler to submit bb castle room data

---

src/options.html

Even as a developer who is intimate with the code, I can _never_ remember what each of these option do and don't do.
Suggestions on wording are welcome.

Clarify horn readiness option's descriptions

---

src/scripts/modules/ajax-handlers/sbFactory.ts
src/scripts/modules/ajax-handlers/sbFactory.types.ts
src/scripts/util/constants.ts
tests/scripts/modules/ajax-handlers/sbFactory.spec.ts

- Migrate deprecated test method calls
- Add Bountiful Beans Snack Pack

Update for SB Factory 2024

---

src/scripts/main.js
src/scripts/modules/stages/environments/sunkenCity.ts
src/scripts/modules/stages/index.ts
src/scripts/modules/stages/legacy.js
src/scripts/types/hg.ts
src/scripts/types/quests/index.ts
src/scripts/types/quests/sunkenCity.ts
tests/scripts/modules/stages/environments/sunkenCity.spec.ts

- Add Sunken City stage test
- Add Sunken City stager

Convert Sunken City stager

---

.github/workflows/publish.yml
package-lock.json
package.json

- Bump package versions
- Drop deprecated flag in web-ext sign

Publish workflow fix with dependency updates

---

src/scripts/hunt-filter/exemptions/environments/draconicDepth.ts
src/scripts/hunt-filter/exemptions/index.ts
src/scripts/modules/stages/environments/draconicDepths.ts
src/scripts/modules/stages/index.ts
src/scripts/types/hg.ts
src/scripts/types/quests/draconicDepths.ts
src/scripts/types/quests/index.ts
tests/scripts/modules/stages/environments/draconicDepths.spec.ts

- Add quest type for Draconic Depths
- Add stages for Draconic Depths
- Add transition exemptions for Draconic Depths

Add support for Draconic Depths

---

src/scripts/modules/ajax-handlers/spookyShuffle.ts
src/scripts/modules/ajax-handlers/spookyShuffle.types.ts
tests/scripts/modules/ajax-handlers/spookyShuffle.spec.ts
tests/utility/builders.ts

- **Migrate obsoleted jest methods**
- **Add builder pattern helper classes**
- **Use Zod to validate Spooky Shuffle responses**

Halloween '24 upgrades

---

.github/dependabot.yml

Weekly is a little bit spammy for the pace of this project.

Increase dependabot schedule to monthly

---

src/scripts/main.js

Payload is exact same. Just new URL.

Change treasuremap helper to new backend url

---

src/scripts/modules/ajax-handlers/sbFactory.ts
src/scripts/modules/ajax-handlers/sbFactory.types.ts
src/scripts/util/constants.ts
tests/scripts/modules/ajax-handlers/sbFactory.spec.ts
tests/utility/builders.ts

- Added Fantasy Fizz snack pack with appropriate ID.
- Migrated SB Factory to use Zod to validate responses.
- SB Factory tests now use response builder.

Update SB Factory handler for 2025

---

package-lock.json
src/manifest.v3.chrome.json
src/manifest.v3.firefox.json
src/scripts/background.js
src/scripts/content.js
src/scripts/main.js

Tested in dev mode chrome and firefox. Did not test with custom URL.

Fix for v3 Alarm Sound Missing

---

src/scripts/background.js

Using setinterval at 1s instead of alarms at 30s

Badge update interval

---

src/scripts/hunt-filter/exemptions/environments/afterwordAcres.ts
src/scripts/hunt-filter/exemptions/index.ts
src/scripts/main.js
src/scripts/modules/details/environments/epilogueFalls.ts
src/scripts/modules/details/index.ts
src/scripts/modules/stages/environments/afterwordAcres.ts
src/scripts/modules/stages/index.ts
src/scripts/types/hg/quests/afterwordAcres.ts
src/scripts/types/hg/quests/epilogueFalls.ts
src/scripts/types/hg/quests/index.ts
tests/scripts/hunt-filter/exemptions/environments/afterwordAcres.spec.ts
tests/scripts/modules/details/environments/epilogueFalls.spec.ts
tests/scripts/modules/stages/environments/afterwordAcres.spec.ts

* **Add minimal quest schemas for AA and EF**
* **Add Afterword Acres stages for blight tiers**
* **Add stage transition exemption for AA blight**
* **Add detailer for Epilogue Falls zone**
* **Add details for Rainbow Quill procs**

Add support for Afterword Acres & Epilogue Falls

---

src/scripts/hunt-filter/messageRules.ts
src/scripts/main.js
src/scripts/types/hg/hgResponse.ts
src/scripts/types/hg/trapImage.ts
src/scripts/types/mhct.ts
tests/scripts/hunt-filter/common.ts
tests/utility/builders.ts

This will require a change on the hunt helper side
Related: https://github.com/m-h-c-t/mh-hunt-helper/issues/222
Closes: #57

Add aura tracking

---

.github/workflows/ci.yml
package-lock.json
package.json
src/scripts/hunt-filter/messageRules.ts
src/scripts/types/hg/convertibleOpen.ts
src/scripts/types/hg/hgResponse.ts
src/scripts/types/mhct.ts
tests/e2e/README.md
tests/e2e/convertible.spec.ts
tests/e2e/hunt.spec.ts
tests/e2e/util/mockServer.ts
tests/e2e/util/openConvertible.ts
tests/e2e/util/setup-env.ts
tests/e2e/util/soundHorn.ts
tests/utility/builders.ts
tests/utility/logging-assertions.ts
tests/utility/stringyObject.ts
vitest.config.ts

Actual integration tests!
These tests simulate the main page script loading and doing the main two things: hunt submission and convertible submission

Add integration tests for hunt and convertible submission
